#!/bin/sh

User_setup ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/user-setup.list ]
	then
		return
	fi

	echo -n " user-setup"

	Configure_user_setup
}

Configure_user_setup ()
{
	# Checking if if package is already configured
	if grep -q "^${USERNAME}" /etc/passwd
	then
		return
	fi

	# Default password is: live
	# passwords can be generated with 'echo "live" | mkpasswd -s',
	# a blank password is 'U6aMy0wojraho'.
	PASSWORD="8Ab05sVQ4LLps"

cat > /tmp/debconf.live << EOF
user-setup passwd/make-user boolean true
user-setup passwd/root-password-crypted string *
user-setup passwd/user-password-crypted string ${PASSWORD}
user-setup passwd/user-fullname string ${USER_FULLNAME}
user-setup passwd/username string ${USERNAME}
user-setup passwd/user-uid string 999
EOF

	debconf-set-selections < /tmp/debconf.live
	rm -f /tmp/debconf.live

	# FIXME
	set +e
	touch /etc/passwd-
	chmod 0600 /etc/passwd-

	/usr/lib/user-setup/user-setup-apply 2>&1 \
	| grep -v "Shadow passwords are now on"
	set -e
}

User_setup
