#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Hostname ()
{
	# Supporting variables within hostnames
	if [ -e /bin/ip ]
	then
		LINK="$(ip -oneline -family link address show dev eth0 | awk '{ print $13 }' | sed -e 's|:|-|g')"
		INET="$(ip -oneline -family inet address show dev eth0 | awk '{ print $4 }' | sed -e 's|\.|-|g' -e 's|/.*||')"
		INET6="$(ip -oneline -family inet6 address show dev eth0 | awk '{ print $4 }' | sed -e 's|:|-|g' -e 's|/.*||' -e 's|--|-|')"
	fi

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.hostname=*|hostname=*)
				LIVE_HOSTNAME="${_PARAMETER#*hostname=}"
				;;
		esac
	done

	# Checking if package is installed or already configured
	if [ -z "${LIVE_HOSTNAME}" ] || \
	   [ -e /var/lib/live/config/hostname ]
	then
		return
	fi

	echo -n " hostname"

	Configure_hostname
}

Configure_hostname ()
{
	# Change hostname only if it is not set
	if [ ! -e /etc/hostname ] || \
	   grep -qs localhost\.localdomain /etc/hostname
	then
		echo "${LIVE_HOSTNAME}" > /etc/hostname
	else
		LIVE_HOSTNAME="$(cat /etc/hostname)"
	fi

	# Create /etc/hosts only if it is not present or empty
	if [ ! -s /etc/hosts ]
	then

cat > /etc/hosts << EOF
127.0.0.1       localhost ${LIVE_HOSTNAME}
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
EOF

	fi

	hostname "${LIVE_HOSTNAME}" || true

	# Creating state file
	touch /var/lib/live/config/hostname
}

Hostname
