#!/bin/sh

Sudo ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/sudo.list ]
	then
		return
	fi

	echo -n " sudo"

	Configure_sudo
}

Configure_sudo ()
{
	# Checking if if package is already configured
	if grep -q "^${USERNAME}" /etc/sudoers
	then
		return
	fi

	echo "${USERNAME}  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

	sudo -u "${USERNAME}" sh -c "echo 'SU_TO_ROOT_SU=sudo' >> /home/${USERNAME}/.su-to-rootrc"

	if [ -x /usr/bin/gconftool-2 ]
	then
		sudo -u "${USERNAME}" gconftool-2 -s -t bool /apps/gksu/sudo-mode true
		sudo -u "${USERNAME}" gconftool-2 -s -t bool /apps/gksu/display-no-pass-info false
	fi

	sudo -u "${USERNAME}" sh -c "umask 0077 && mkdir -p /home/${USERNAME}/.kde/share/config && cat > /home/${USERNAME}/.kde/share/config/kdesurc" << EOF
[super-user-command]
super-user-command=sudo
EOF

	if [ -e /usr/share/apps/konsole/sumc.desktop ]
	then
		sudo -u "${USERNAME}" sh -c "umask 0077 && mkdir -p /home/${USERNAME}/.kde/share/apps/konsole && sed -e's/Exec=su.*$/Exec=sudo mc -c/' /usr/share/apps/konsole/sumc.desktop > /home/${USERNAME}/.kde/share/apps/konsole/sumc.desktop"
	fi

	if [ -e /usr/share/apps/konsole/su.desktop ]
	then
		sudo -u "${USERNAME}" sh -c "umask 0077 && mkdir -p /home/${USERNAME}/.kde/share/apps/konsole && sed -e's/Exec=su.*$/Exec=sudo -i/' /usr/share/apps/konsole/su.desktop > /home/${USERNAME}/.kde/share/apps/konsole/su.desktop"
	fi
}

Sudo
