#!/bin/sh

Tzdata ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/tzdata.list ] || \
	   [ -e /var/lib/live/config/tzdata ]
	then
		return
	fi

	echo -n " tzdata"

	Configure_tzdata
}

Configure_tzdata ()
{
	if [ -n "${LIVE_TIMEZONE}" ]
	then
		_AREA="$(echo ${LIVE_TIMEZONE} | cut -f1 -d '/')"
		_ZONE="$(echo ${LIVE_TIMEZONE} | cut -f2 -d '/')"

debconf-communicate -fnoninteractive live-config > /dev/null << EOF
set tzdata/Areas ${_AREA}
set tzdata/Zones/${_AREA} ${_ZONE}
EOF

		cp -f /usr/share/zoneinfo/${_AREA}/${_ZONE} /etc/localtime
	else

debconf-communicate -fnoninteractive live-config > /dev/null << EOF
set tzdata/Areas Etc
set tzdata/Zones/Etc UTC
EOF

		cp -f /usr/share/zoneinfo/UTC /etc/localtime
	fi

	if [ -n "${LIVE_UTC}" ]
	then
		sed -i -e "s|UTC=.*|UTC=${LIVE_UTC}|" /etc/default/rcS
	fi

	# Creating state file
	touch /var/lib/live/config/tzdata
}

Tzdata
