#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Locales_all ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/locales-all.list ] || \
	   [ -e /var/lib/live/config/locales-all ]
	then
		return
	fi

	echo -n " locales-all"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.locales=*|locales=*)
				LIVE_LOCALES="${_PARAMETER#*locales=}"
				;;
		esac
	done

	Configure_locales_all
}

Configure_locales_all ()
{
	if [ -n "${LIVE_LOCALES}" ]
	then
		LIVE_LOCALES="$(echo ${LIVE_LOCALES} | awk -F, '{ print $1 }')"
	else
		LIVE_LOCALES="en_US.UTF-8"
	fi

	if [ -e /etc/progress-linux_version ]
	then
		sed -i -e "s|^ *export LANG=.*|export LANG=\"${LIVE_LOCALES}\"|" /etc/profile
	else
		printf 'export LANG="%s"\n' "${_LOCALE}" > /etc/profile.d/zz-live-config_locales-all.sh
	fi

	# Creating state file
	touch /var/lib/live/config/locales-all
}

Locales_all
