#!/bin/sh

Gdm3 ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/gdm3.list ] || \
	   [ -e /var/lib/live/config/gdm3 ]
	then
		return
	fi

	echo -n " gdm3"

	Configure_gdm3
}

Configure_gdm3 ()
{
	# Checking if if package is already configured differently
	if grep -qs AutomaticLoginEnable /etc/gdm3/daemon.conf
	then
		return
	fi

	_GDM3_OPTIONS="AutomaticLoginEnable=true\n\
AutomaticLogin=${LIVE_USERNAME}\n\
TimedLoginEnable=true\n\
TimedLogin=${LIVE_USERNAME}\n\
TimedLoginDelay=10"

	sed -i -e "s|\[daemon\]|\[daemon\]\n${_GDM3_OPTIONS}|" /etc/gdm3/daemon.conf

	# Creating state file
	touch /var/lib/live/config/gdm3
}

Gdm3
