#!/bin/sh

Kdm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kdm.list ] || \
	   [ -e /var/lib/live/config/kdm ]
	then
		return
	fi

	echo -n " kdm"

	Configure_kdm
}

Configure_kdm ()
{
	if [ -e /etc/kde4/kdm/kdmrc ]
	then
		# squeeze

		# autologin
		sed -i -r -e "s|^#?AutoLoginEnable=.*\$|AutoLoginEnable=true|" \
			  -e "s|^#?AutoLoginAgain=.*\$|AutoLoginAgain=true|" \
			  -e "s|^#?AutoLoginUser=.*\$|AutoLoginUser=${LIVE_USERNAME}|" \
		/etc/kde4/kdm/kdmrc

		# language
		if [ -n "${_LANGUAGE}" ]
		then
			sed -i -r -e "s|^#?Language=.*\$|Language=${_LANGUAGE}|" \
				/etc/kde4/kdm/kdmrc
		fi
	elif [ -e /etc/kde3/kdm/kdmrc ]
	then
		# lenny

		# autologin
		sed -i -r -e "s|^#?AutoLoginEnable=.*\$|AutoLoginEnable=true|" \
			  -e "s|^#?AutoLoginAgain=.*\$|AutoLoginAgain=true|" \
			  -e "s|^#?AutoLoginUser=.*\$|AutoLoginUser=${LIVE_USERNAME}|" \
		/etc/kde3/kdm/kdmrc

		# language
		if [ -n "${_LANGUAGE}" ]
		then
			sed -i -r -e "s|^#?Language=.*\$|Language=${_LANGUAGE}|" \
				/etc/kde3/kdm/kdmrc
		fi
	fi

	# Creating state file
	touch /var/lib/live/config/kdm
}

Kdm
