#!/bin/sh

Lxdm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/lxdm.list ] || \
	   [ -e /var/lib/live/config/lxdm ]
	then
		return
	fi

	echo -n " lxdm"

	Configure_lxdm
}

Configure_lxdm ()
{
	if [ -e /etc/lxdm/lxdm.conf ]
	then
		sed -i -r -e "s|^#?autologin=.*\$|autologin=${LIVE_USERNAME}|" \
			  -e "s|^#?session.*\$|session|" \
		/etc/lxdm/lxdm.conf
	fi

	# Creating state file
	touch /var/lib/live/config/lxdm
}

Lxdm
