#!/bin/sh

Nodm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/nodm.list ] || \
	   [ -e /var/lib/live/config/nodm ]
	then
		return
	fi

	echo -n " nodm"

	Configure_nodm
}

Configure_nodm ()
{

cat > /tmp/debconf.live << EOF
nodm nodm/enabled boolean true
nodm nodm/user string ${LIVE_USERNAME}
EOF

	debconf-set-selections < /tmp/debconf.live
	rm -f /tmp/debconf.live

	dpkg-reconfigure -f non-interactive -p critical nodm

	# Creating state file
	touch /var/lib/live/config/nodm
}

Nodm
