#!/bin/sh

Apport ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/apport.list ] || \
	   [ -e /var/lib/live/apport ]
	then
		return
	fi

	echo -n " apport"

	Configure_apport
}

Configure_apport ()
{
	# Enabling detection of crashes
	sed -i -e 's|enabled=0|enabled=1|' /etc/default/apport

	# Creating state file
	touch /var/lib/live/config/apport
}

Apport
