#!/bin/sh

Kaboom ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kaboom.list ] || \
	   [ -e /var/lib/live/config/kaboom ]
	then
		return
	fi

	echo -n " kaboom"

	Configure_kaboom
}

Configure_kaboom ()
{
	mkdir -p /home/${LIVE_USERNAME}/.local
	touch /home/${LIVE_USERNAME}/.local/kaboom

	# Creating state file
	touch /var/lib/live/config/kaboom
}

Kaboom
