#!/bin/sh

Kpersonalizer ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kpersonalizer.list ] || \
	   [ -e /var/lib/live/config/kpersonalizer ]
	then
		return
	fi

	echo -n " kpersonalizer"

	Configure_kpersonalizer
}

Configure_kpersonalizer ()
{
	# Checking if apckage is already configured differently
	if grep -qs FirstLogin /etc/kde3/kpersonalizerrc
	then
		return
	fi

cat > /etc/kde3/kpersonalizerrc << EOF
[General]
FirstLogin=false
EOF

	# Creating state file
	touch /var/lib/live/config/kpersonalizer
}

Kpersonalizer
