#!/bin/sh

Kpersonalizer ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/kpersonalizer.list ]
	then
		return
	fi

	echo -n " kpersonalizer"

	Configure_kpersonalizer
}

Configure_kpersonalizer ()
{
	# Checking if apckage is already configured
	if grep -qs FirstLogin /etc/kde3/kpersonalizerrc
	then
		return
	fi

cat > /etc/kde3/kpersonalizerrc << EOF
[General]
FirstLogin=false
EOF

}

Kpersonalizer
