#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Ssl_cert ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/ssl-cert.list ] || \
	   [ -e /var/lib/live/config/ssl-cert ]
	then
		return
	fi

	echo -n " ssl-cert"

	Configure_ssl_cert
}

Configure_ssl_cert ()
{
	make-ssl-cert generate-default-snakeoil --force-overwrite

	# Creating state file
	touch /var/lib/live/config/ssl-cert
}

Ssl_cert
