#!/bin/sh

Sslcert ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/sslcert.list ] || \
	   [ -e /var/lib/live/config/sslcert ]
	then
		return
	fi

	echo -n " sslcert"

	Configure_sslcert
}

Configure_sslcert ()
{
	make-ssl-cert generate-default-snakeoil --force-overwrite

	# Creating state file
	touch /var/lib/live/config/sslcert
}

Sslcert
