#!/bin/sh

# live-config(7) - System Configuration Scripts
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.


Hooks ()
{
	if [ -z "${LIVE_HOOKS}" ]
	then
		return
	fi

	echo -n " hooks"

	Process_hooks
}

Process_hooks ()
{
	for _HOOK in $(echo ${LIVE_HOOKS} | sed -e 's/|/ /g')
	do
		_TMPFILE="$(mktemp -t live-config.XXXXXXXX)"

		if $(echo "${_HOOK}" | grep file:\/\/)
		then
			# local file
			cp $(echo ${_HOOK} | sed 's|file\://||') "${_TMPFILE}"
		else
			# remote file

			if [ -z "${_NETWORK}" ] && [ -e /etc/init.d/live-config ]
			then
				/etc/init.d/mountkernfs.sh start > /dev/null 2>&1
				/etc/init.d/mountdevsubfs.sh start > /dev/null 2>&1
				/etc/init.d/ifupdown-clean start > /dev/null 2>&1
				/etc/init.d/ifupdown start > /dev/null 2>&1
				/etc/init.d/networking start > /dev/null 2>&1

				_NETWORK="true"
				export _NETWORK
			fi

			wget --quiet "${_HOOK}" -O "${_TMPFILE}"
		fi

		chmod 0755 "${_TMPFILE}"
		./"${_TMPFILE}"
		rm -f "${_TMPFILE}"
	done
}

Hooks
