#!/bin/sh

Hook ()
{
	if [ -z "${LIVE_HOOK}" ]
	then
		return
	fi

	echo -n " hook"

	Process_hook
}

Process_hook ()
{
	for _HOOK in $(echo ${LIVE_HOOK} | sed -e 's/|/ /g')
	do
		_TMPFILE="$(mktemp -t live-config.XXXXXXXX)"

		if $(echo "${_HOOK}" | grep file:\/\/)
		then
			# local file
			cp $(echo ${_HOOK} | sed 's|file\://||') "${_TMPFILE}"
		else
			# remote file

			if [ -z "${_NETWORK}" ] && [ -e /etc/init.d/live-config ]
			then
				/etc/init.d/mountkernfs.sh start > /dev/null 2>&1
				/etc/init.d/mountdevsubfs.sh start > /dev/null 2>&1
				/etc/init.d/ifupdown-clean start > /dev/null 2>&1
				/etc/init.d/ifupdown start > /dev/null 2>&1
				/etc/init.d/networking start > /dev/null 2>&1

				_NETWORK="true"
			fi

			wget --quiet "${_HOOK}" -O "${_TMPFILE}"
		fi

		chmod 0755 "${_TMPFILE}"
		./"${_TMPFILE}"
		rm -f "${_TMPFILE}"
	done
}

Hook
