#!/bin/sh

set -e

. /usr/share/debconf/confmodule

Defaults ()
{
	if [ -z "${_ENABLE}" ]
	then
		if [ -n "$(cat /selinux/enforce 2> /dev/null)" ]
		then
			case "$(cat /selinux/enforce 2> /dev/null)" in
				0)
					_ENABLE="false"
					;;

				1)
					_ENABLE="true"
					;;
			esac
		else
			_ENABLE="false"
		fi
	fi
}

#db_get live-debconfig/selinux/enable
#_ENABLE="${RET}" # boolean

Defaults

db_set live-debconfig/selinux/enable "${_ENABLE}"
db_fset live-debconfig/selinux/enable seen false

db_settitle live-debconfig/title
db_input high live-debconfig/selinux/enable || true
db_go

db_get live-debconfig/selinux/enable
_ENABLE="${RET}" # boolean

#Defaults

db_stop

case "${_ENABLE}" in
	true)
		rm -f /selinux/enforce
		rmdir --ignore-fail-on-non-empty /selinux > /dev/null 2>&1 || true
		;;

	false)
		mkdir -p /selinux
		echo 0 > /selinux/enforce
		;;
esac
