#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

if [ -e /bin/live-config ]
then
	/bin/live-config
fi

/sbin/init.orig "${@}"

sleep
