#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

Init ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/update-notifier.list ] || \
	   [ -e /var/lib/live/config/update-notifier ]
	then
		exit 0
	fi

	echo -n " update-notifier"
}

Config ()
{
	# For GNOME, we divert away apt-check to avoid a regular
	# 'apt-get update' equivalent in the live session. We want to run
	# update-notifier for crash report handling.

	# Diverting /usr/lib/update-notifier/apt-check
	if [ ! -e /usr/lib/update-notifier/apt-check.orig.update-notifier-common ]
	then
		dpkg-divert --quiet --package live-config --add --rename --divert /usr/lib/update-notifier/apt-check.orig.update-notifier-common /usr/lib/update-notifier/apt-check

		ln -sf /bin/true /usr/lib/update-notifier/apt-check
	fi

	# For KDE, adept_notifier's only useful function at the moment is an
	# 'apt-get update' equivalent, so we disable it entirely.
	rm -f /usr/share/autostart/adept_notifier_auto.desktop

	# Creating state file
	touch /var/lib/live/config/update-notifier
}

Init
Config
