#!/bin/sh

## live-config-foobar(7) - Additional Configuration Scripts for Debian Live
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
## Copyright (C) 2012 John Doe <john@example.org>
##
## live-config-foobar comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Foobar ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/foobar.list ] || \
	   [ -e /var/lib/live/config/foobar ]
	then
		return
	fi

	echo -n " foobar"

	# Boot parameters can be acted up either this way...
	if ! echo ${_CMDLINE} | grep -qs "example.foobar" && \
	   ! echo ${_CMDLINE} | grep -qs "foobar"
	then
		return
	fi

	# ...or if you want to specify certain options:
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			example.foobar=*|foobar=*)
				EXAMPLE_FOOBAR="${_PARAMETER#*foobar=}"
				;;
		esac
	done

	Configure_foobar
}

Configure_foobar ()
{
	# Configuring foobar either this way...
	if [ -n "${EXAMPLE_FOOBAR}" ]
	then
		sleep 1
	fi

	# ...or if you want to specify certain options:
	case "${EXAMPLE_FOOBAR}" in
		foo)
			sleep 1
			;;
	esac

	# Creating state file
	touch /var/lib/live/config/foobar
}

Foobar
