#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Gnome_screensaver ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/gnome-screensaver.list ] || \
	   [ -e /var/lib/live/config/gnome-screensaver ]
	then
		return
	fi

	echo -n " gnome-screensaver"

	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_gnome_screensaver
}

Configure_gnome_screensaver ()
{
	# Disabling to lock the screen when the screensaver goes active.
	sudo -u "${LIVE_USERNAME}" gsettings set org.gnome.desktop.screensaver lock-enabled false

	# Creating state file
	touch /var/lib/live/config/gnome-screensaver
}

Gnome_screensaver
