#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/ureadahead.list ] || \
	   [ -e /var/lib/live/config/ureadahead ]
	then
		exit 0
	fi

	echo -n " ureadahead"
}

Config ()
{
	# Disabling ureadahead
	rm -f /etc/init/ureadahead*.conf

	# Creating state file
	touch /var/lib/live/config/ureadahead
}

Init
Config
