.TH LIVE\-CONFIG 7 2010\-05\-24 2.0~a1 "Debian Live Project"

.SH NAME
\fBlive\-config\fR \- System Configuration Scripts

.SH DESCRIPTION
\fBlive\-config\fR contains the scripts that configure a Debian Live system during the boot process (late userspace).

.SH CONFIGURATION
\fBlive\-config\fR can be configured through a boot parameter or a configuration file.

.SS Kernel Parameters
\fBlive\-config\fR is only activated if 'live\-config', 'live\-config=\fISCRIPT\fR', or 'live\-config=\fISCRIPT1\fR,\fISCRIPT2\fR,...\fISCRIPTN\fR' was used as a kernel parameter.
.PP
If no script is specified (default), then all scripts are executed. This is the same as using 'live\-config=all'.
.PP
If no script should be execured, 'live\-config=none' can be used.
.PP
If some scripts are specified, then only those scripts are executed. Note that the order matters, e.g. 'live\-config=sudo,user-setup' would not work since the user needs to be added before it can be configured for sudo. Look at the filenames of the scripts in /lib/live/config for their ordering number.

.SS Configuration Files
\fBlive\-config\fR can be configured (but not activated) through configuration files. Those files can be placed either in the root filesystem itself (/etc/live/config.conf), or on the live media (live/config.conf).

.SH SCRIPTS
\fBlive\-config\fR currently features the following scripts in /lib/live/config.
.IP "\fBhostname\fR" 4
configures /etc/hostname and /etc/hosts.
.IP "\fBuser-setup\fR" 4
adds an live user account.
.IP "\fBsudo\fR" 4
grants sudo privileges to the live user.
.IP "\fBtzdata\fR" 4
configures /etc/timezone.
.IP "\fBgdm\fR" 4
configures autologin in gdm (lenny).
.IP "\fBgdm3\fR" 4
configures autologin in gdm3 (squeeze and newer).
.IP "\fBkdm\fR" 4
configures autologin in kdm.
.IP "\fBlxdm\fR" 4
configures autologin in lxdm.
.IP "\fBnodm\fR" 4
configures autologin in nodm.
.IP "\fBapport\fR" 4
enables apport.
.IP "\fBgnome-panel-data\fR" 4
disables lock button for the screen.
.IP "\fBgnome-power-manager\fR" 4
disables hibernation.
.IP "\fBgnome-screensaver\fR" 4
disables the screensaver locking the screen.
.IP "\fBinitramfs-tools\fR" 4
makes update-initramfs to also update the live media when using persistency.
.IP "\fBkaboom\fR" 4
disables kde migration wizard (squeeze and newer).
.IP "\fBkde-services\fR" 4
disables some unwanted KDE services (squeeze and newer).
.IP "\fBkpersonalizer\fR" 4
disables kde configuration wizard (lenny).
.IP "\fBlive-installer-launcher\fR" 4
adds live-installer-launcher on users desktop.
.IP "\fBmodule-init-tools\fR" 4
automatically load some modules on some architectures.
.IP "\fBpolicykit\fR" 4
grant user privilegies through policykit.
.IP "\fBsslcert\fR" 4
regenerating ssl snake-oil certificates.
.IP "\fBupdate-notifier\fR" 4
disables update-notifier.
.IP "\fBhook\fR" 4
allows to run arbitrary commands from a script placed on the live media or an http/ftp server.

.SH FILES
.IP "\fB/etc/live/config.conf\fR" 4
.IP "\fBlive/config.conf\fR" 4
.IP "\fB/lib/live/config.sh\fR" 4
.IP "\fB/lib/live/config/\fR" 4

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
\fIlive\-initramfs\fR(7)

.SH HOMEPAGE
More information about live\-config and the Debian Live project can be found on the homepage at <\fIhttp://live.debian.net/\fR> and in the manual at <\fIhttp://live.debian.net/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-config package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Debian Live mailing list at <\fIdebian-live@lists.debian.org\fR>.

.SH AUTHOR
live\-config was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
