#!/bin/sh

# live-config(7) - System Configuration Scripts
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.


Foo ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/foo.list ] || \
	   [ -e /var/lib/live/config/foo ]
	then
		return
	fi

	echo -n " foo"

	Configure_foo
}

Configure_foo ()
{
	# Checking if package is already configured
	sleep 1

	# Boot parameters can be acted up either this way...
	if ! grep -qs "live-helper.foo" /proc/cmdline
	then
		return
	fi

	# ...or if you want to specify certain options:
	for _PARAMETER in $(cat /proc/cmdline)
	do
		case "${_PARAMETER}" in
			live-config.foo=*)
				LIVE_FOO="${_PARAMETER#live-config.foo=}"
				;;
		esac
	done

	# Configuring foo
	sleep 1

	# Creating state file
	touch /var/lib/live/config/foo
}

Foo
