#!/bin/sh

Foo ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/foo.list ] || \
	   [ -e /var/lib/live/config/foo ]
	then
		return
	fi

	echo -n " foo"

	Configure_foo
}

Configure_foo ()
{
	# Checking if apckage is already configured
	sleep 1

	# Configuring foo
	sleep 1

	# Creating state file
	touch /var/lib/live/config/foo
}

Foo
